apiVersion: v1
description: A Helm chart for Jenkins X Serverless
name: jenkins-x-serverless
version: 0.0.1-SNAPSHOT
icon: https://cdn.jsdelivr.net/gh/jenkins-x/jenkins-x-platform@08df980/images/kubernetes.png
